# Generated by Django 5.0.1 on 2024-01-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coder_number', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('lc_id', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
